services:
  web:
    build: .
    container_name: bsa_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/apache2/ssl
    depends_on:
      - db

  db:
    image: mariadb
    container_name: bsa_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bsa_db
      MYSQL_USER: bsa
      MYSQL_PASSWORD: bsapass
    volumes:
      # - db_data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d/
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bsa_pma
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
# volumes:
#   db_data: